#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely. With a sleep 2 in between each iteration.I am invincible!!! when receiving a SIGTERM signal
touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
function finish(){
	echo
}
trap finish SIGINT
trap 'echo I hate the kill command; exit $?' TERM
trap 'echo Y U no love me?!; exit $?' INT
trap 'rm /var/run/myscript.pid; exit $?' QUIT
while :
do
	echo "To infinity and beyond"
	sleep 1
done
