#!/usr/bin/env bash
# This script the content of the file /etc/passwd
f="/etc/passwd"
if [ -e "$f" ]
then
	while read -r line; do
		readarray -d : -t strarr <<< "$line"
                echo "${strarr[0]}:${strarr[2]}:${strarr[5]}"
	done <$f
fi
