#!/usr/bin/env bash
# This script the content of the file /etc/passwd
f="/etc/passwd"
if [ -e "$f" ]
then
	IFS=':'
	while read -r line; do
		read -ra strarr <<< "$line"
                echo "The user ${strarr[0]} is part of the ${strarr[3]} gang, lives in ${strarr[5]} and rides ${strarr[6]}. ${strarr[2]}'s place is protected by the passcode ${strarr[1]}, more info about the user here: ${strarr[0]}"
	done <$f
fi
