#!/usr/bin/env bash
# This script 
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed
# using for loop
# Do not display hidden files
LIST="$(ls)"
for i in $LIST ;
do
	echo "${i#*-}"
done
