#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except TCP ports 22, 443 and 80
apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw disable
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
